### ISSUE TITLE
model pool evaluation fail with FileNotFoundError (sumo_env.conf)

### ISSUE THREAD

**Issue by kclim2** [wingsweihua/colight#14]
==============  model pool evaluation =============
========================================================in model_pool_wrapper print dic_exp_conf
{'RUN_COUNTS': 3600, 'TRAFFIC_FILE': ['anon_6_6_300_0.3_bi.json'], 'MODEL_NAME': 'CoLight', 'NUM_ROUNDS': 60, 'NUM_GENERATORS': 4, 'LIST_MODEL': ['Fixedtime', 'SOTL', 'Deeplight', 'SimpleDQN'], 'LIST_MODEL_NEED_TO_UPDATE': ['Deeplight', 'SimpleDQN', 'CoLight', 'GCN', 'SimpleDQNOne', 'Lit'], 'MODEL_POOL': True, 'NUM_BEST_MODEL': 3, 'PRETRAIN': False, 'PRETRAIN_MODEL_NAME': 'CoLight', 'PRETRAIN_NUM_ROUNDS': 0, 'PRETRAIN_NUM_GENERATORS': 15, 'AGGREGATE': False, 'DEBUG': False, 'EARLY_STOP': False, 'MULTI_TRAFFIC': False, 'MULTI_RANDOM': False, 'ROADNET_FILE': 'roadnet_6_6.json'}
{'RUN_COUNTS': 3600, 'TRAFFIC_FILE': ['anon_6_6_300_0.3_bi.json'], 'MODEL_NAME': 'CoLight', 'NUM_ROUNDS': 60, 'NUM_GENERATORS': 4, 'LIST_MODEL': ['Fixedtime', 'SOTL', 'Deeplight', 'SimpleDQN'], 'LIST_MODEL_NEED_TO_UPDATE': ['Deeplight', 'SimpleDQN', 'CoLight', 'GCN', 'SimpleDQNOne', 'Lit'], 'MODEL_POOL': True, 'NUM_BEST_MODEL': 3, 'PRETRAIN': False, 'PRETRAIN_MODEL_NAME': 'CoLight', 'PRETRAIN_NUM_ROUNDS': 0, 'PRETRAIN_NUM_GENERATORS': 15, 'AGGREGATE': False, 'DEBUG': False, 'EARLY_STOP': False, 'MULTI_TRAFFIC': False, 'MULTI_RANDOM': False, 'ROADNET_FILE': 'roadnet_6_6.json'}
Start testing model pool
Process Process-1:313:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/colight/pipeline.py", line 218, in model_pool_wrapper
    model_pool.model_compare(cnt_round)
  File "/colight/model_pool.py", line 179, in model_compare
    dic_sumo_env_conf = json.load(open(os.path.join(records_dir, "sumo_env.conf"), "r"))
FileNotFoundError: [Errno 2] No such file or directory: 'records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_30_07_15_44/sumo_env.conf'
model_pool to join
model_pool finish join

the available conf files in the folder are as follow:

records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_30_07_15_44/agent.conf
records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_30_07_15_44/exp.conf
records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_30_07_15_44/test_exp.conf
records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_30_07_15_44/traffic_env.conf

**Comment by wingsweihua** [comment]
SUMO is not supported in our current version.
