### ISSUE TITLE
How do you calculate the travel time metric based on the code?

### ISSUE THREAD

**Issue by lastditch222** [wingsweihua/colight#3]
Hello, how do you calculate the travel time metric based on the code? It seems you calculate each vehicle's start and end time when passing each intersection, then how do you get the average travel time for all the vehicles? Thanks.

**Comment by wingsweihua** [comment]
The travel time for all vehicles is calculated through the concatenation among several intersections.  An updated summary file is updated for you reference.

**Comment by kclim2** [comment]
The only summary python script i can find in the repository is https://github.com/wingsweihua/colight/blob/master/summary_multi_anon.py

is that the python script i can use to produce the travel time metric?

I try to run the summary_multi_anon.py and fail with the error message inter_0.pkl not found

root@3f82bba33fa6:/colight# python summary_multi_anon.py --memo /colight/records/0515_afternoon_Colight_6_6_bi -b 
anon_6_6_300_0.3_bi.json_04_29_02_47_21
Traceback (most recent call last):
  File "summary_multi_anon.py", line 691, in <module>
    summary_detail_baseline(args.memo)
  File "summary_multi_anon.py", line 489, in summary_detail_baseline
    if os.path.getsize(os.path.join(train_dir, "inter_0.pkl")) > 0:
  File "/opt/conda/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/inter_0.pkl'

the available inter_0.pkl is in my folder 
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/test_round/round_0/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/test_round/round_1/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/test_round/round_2/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/test_round/round_3/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/test_round/round_4/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/total_samples_inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_0/generator_0/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_0/generator_1/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_0/generator_2/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_0/generator_3/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_1/generator_0/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_1/generator_1/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_1/generator_2/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_1/generator_3/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_2/generator_0/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_2/generator_1/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_2/generator_2/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_2/generator_3/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_3/generator_0/inter_0.pkl
colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_3/generator_1/inter_0.pkl
colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_3/generator_2/inter_0.pkl
colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_3/generator_3/inter_0.pkl
colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_4/generator_0/inter_0.pkl
colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_4/generator_1/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_4/generator_2/inter_0.pkl
/colight/records/0515_afternoon_Colight_6_6_bi/anon_6_6_300_0.3_bi.json_04_29_02_47_21/train_round/round_4/generator_3/inter_0.pkl

need your help to point out the correct use of summary_multi_anon.py to generate the performance  (e.g. travel time) of the coLight agent.

**Comment by kclim2** [comment]
summary_multi_anon.py is running okay after i pointed it to record folder with rerun the experiment. but may i know which file specific the travel time?

**Comment by LuckyLeeLL** [comment]
> summary_multi_anon.py is running okay after i pointed it to record folder with rerun the experiment. but may i know which file specific the travel time?
Excuse me, the the inter_{I},pkl of  train_round or the test_round are empty, do you have same question? How did you solve it？

**Comment by LJW0306** [comment]
@kclim2 你好可以给你的联系方式吗 想和您交流一下
