### ISSUE TITLE
RuntimeError: Json parsing error

### ISSUE THREAD

**Issue by 666github100** [wingsweihua/colight#45]
I encountered a very strange thing. The first time I reproduced the code, I did not encounter this error, but the second time, I encountered:
Traceback (most recent call last):
  File "/home/user/.conda/envs/traffic/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.conda/envs/traffic/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/user/colight/pipeline.py", line 189, in generator_wrapper
    best_round=best_round
  File "/data1/user/colight/generator.py", line 31, in __init__
    self.env.reset()
  File "/data1/user/colight/anon_env.py", line 822, in reset
    self.eng = engine.Engine(new_path, thread_num=1)
RuntimeError: Json parsing error

I feel very puzzled. I have looked at the  homepage of  cityflow ,and the configuration file for cityflow.Engine() should be right. Why does it indicate 'RuntimeError: Json parsing error'? Does any friend  help me ?I would appreciate it !

**Comment by LJW0306** [comment]
您好 可以和您交流一下吗

**Comment by 666github100** [comment]
> 您好 可以和您交流一下吗

好滴，欢迎交流呢

**Comment by LJW0306** [comment]
加个联系方式吧。Ljw_36




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wingsweihua/colight"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wingsweihua/colight] RuntimeError: Json parsing error (Issue #45)





  
您好 可以和您交流一下吗
  
好滴，欢迎交流呢

**Comment by wingsweihua** [comment]
Hey @666github100 and @LJW0306 Just to let you know that we are now actively maintaining CoLight under a different repository: [LibSignal](https://darl-libsignal.github.io/) which supports flexible and cross-platform training. We also actively looking for contributions for LibSignal, feel free to reach out if you would love to contribute to the project!

**Comment by LJW0306** [comment]
> 嘿@666github100和@LJW0306只是想让您知道，我们现在正在不同的存储库下积极维护 CoLight：支持灵活和跨平台培训的[LibSignal 。](https://darl-libsignal.github.io/)我们还积极为 LibSignal 寻找贡献，如果您愿意为该项目做出贡献，请随时与我们联系！
I would like to communicate with you. How can I contact you?

**Comment by LJW0306** [comment]
@wingsweihua I would like to communicate with you. How can I contact you?

**Comment by wingsweihua** [comment]
> @wingsweihua I would like to communicate with you. How can I contact you?

Can you can send me an email: https://web.njit.edu/~hw32/

**Comment by LJW0306** [comment]
@wingsweihua I have reviewed your requirements and feel that my own abilities are insufficient to apply for your project.
